# nixos/iso.nix
#
# Configura el sistema como una ISO live booteable.
#
# Importa el módulo `iso-image.nix` de NixOS, que provee toda la maquinaria
# para empaquetar el sistema como una imagen ISO9660 con bootloader
# (isolinux/grub para BIOS, systemd-boot/grub para UEFI).
#
# El resultado es una ISO híbrida: se puede flashear con `dd`/`rufus`/balenaEtcher
# a un USB y bootea tanto en máquinas BIOS como UEFI. El iMac 2014 tiene UEFI
# (con quirks Apple), así que la rama UEFI es la que importa.
{ config, lib, pkgs, modulesPath, jarvisVersion, jarvisPackages, ... }:
let
  # ─── Boot splash ───
  # Renderiza el SVG canónico de jarvis-os a PNG 1920x1080 en build time
  # via librsvg. Reproducible (mismo SVG → mismo hash). Background del
  # splash forzado a #02060e (paleta bg jarvis-os) para que coincida con
  # el resto del HUD.
  bootSplashPng = pkgs.runCommand "jarvis-boot-splash.png" {
    buildInputs = [ pkgs.librsvg ];
  } ''
    ${pkgs.librsvg}/bin/rsvg-convert \
      -w 1920 -h 1080 \
      -b "#02060e" \
      ${../jarvis_hud_voz_circular.svg} \
      -o $out
  '';

  # Path al archivo de credenciales/env fuera del repo. Construido por el
  # builder a partir de su .env personal. Si no existe, IronClaw arrancará
  # sin keys y reclamará al primer uso — eso es el modo "compartible" del ISO.
  jarvisEnvPath = "/home/nexus/.local/share/jarvis-os-secrets/env";

  # Wrapper que arranca hyprpaper y aplica wallpaper a TODOS los monitores
  # detectados en runtime. Independiente del nombre del monitor — corregido
  # en v9 tras el bug de v7/v8 donde el apply hardcoded a `eDP-1` no surtía
  # efecto silenciosamente.
  #
  # Diseño:
  #   1. Lanza hyprpaper en background (preload + IPC on, definido en
  #      `system.activationScripts.jarvisHyprpaperConfig` de desktop.nix).
  #   2. Polleo el socket de Hyprland hasta que responda (max 10s).
  #   3. `hyprctl monitors -j` para enumerar los monitores activos.
  #   4. Para cada uno, `hyprctl hyprpaper wallpaper "$NAME,$PATH"`.
  startWallpaperScript = pkgs.writeShellScriptBin "start-jarvis-wallpaper" ''
    set -e
    LOG=/tmp/jarvis-wallpaper.log
    : > "$LOG"
    exec >> "$LOG" 2>&1

    echo "[$(date -Iseconds)] start-jarvis-wallpaper begin"

    # Lanza el daemon en background. Si ya corre (idempotente), lo matamos
    # para reiniciar con config fresh.
    pkill -x hyprpaper || true
    sleep 0.5
    ${pkgs.hyprpaper}/bin/hyprpaper -c "$HOME/.config/hypr/hyprpaper.conf" &
    HYPRPAPER_PID=$!
    echo "hyprpaper launched, PID $HYPRPAPER_PID"

    # Espera a que Hyprland tenga su socket disponible (max ~10s).
    SOCKDIR="$XDG_RUNTIME_DIR/hypr"
    for i in $(seq 1 20); do
      if [ -d "$SOCKDIR" ] && ls "$SOCKDIR" >/dev/null 2>&1; then
        SIG=$(ls "$SOCKDIR" | head -1)
        if [ -n "$SIG" ] && [ -e "$SOCKDIR/$SIG/.socket.sock" ]; then
          break
        fi
      fi
      sleep 0.5
    done

    if [ -z "''${SIG:-}" ]; then
      echo "ERROR: HYPRLAND_INSTANCE_SIGNATURE no encontrado tras 10s"
      exit 1
    fi
    export HYPRLAND_INSTANCE_SIGNATURE=$SIG
    echo "Hyprland signature: $SIG"

    # Espera adicional a que hyprpaper responda al socket IPC.
    for i in $(seq 1 20); do
      if ${pkgs.hyprland}/bin/hyprctl hyprpaper listloaded >/dev/null 2>&1; then
        break
      fi
      sleep 0.3
    done

    # Aplica wallpaper a cada monitor enumerado dinámicamente.
    WALLPAPER=$(${pkgs.gnugrep}/bin/grep '^preload' "$HOME/.config/hypr/hyprpaper.conf" | ${pkgs.coreutils}/bin/cut -d= -f2 | ${pkgs.coreutils}/bin/tr -d ' ')
    echo "wallpaper path: $WALLPAPER"

    MONITORS=$(${pkgs.hyprland}/bin/hyprctl monitors -j | ${pkgs.jq}/bin/jq -r '.[].name')
    echo "monitors detected: $MONITORS"

    for MON in $MONITORS; do
      echo "applying $WALLPAPER to $MON"
      ${pkgs.hyprland}/bin/hyprctl hyprpaper wallpaper "$MON,$WALLPAPER" || \
        echo "WARN: apply failed for $MON"
    done

    echo "[$(date -Iseconds)] start-jarvis-wallpaper done"
    # Mantener vivo el script para que systemd-user lo trate como service "running".
    # (No estrictamente necesario con uwsm app, pero claro de leer.)
    wait $HYPRPAPER_PID
  '';

  # Wrapper que sourcea /etc/jarvis/env, mete defaults stateless, y arranca
  # IronClaw en modo interactivo (REPL TUI). Es el punto de entrada user-facing.
  jarvisChatScript = pkgs.writeShellScriptBin "jarvis-chat" ''
    set -euo pipefail

    # IronClaw usa dotenvy::override_load() — el archivo `~/.ironclaw/.env`
    # GANA contra exports de shell. Por eso lo escribimos nosotros fresh
    # en cada boot, mezclando defaults stateless + secrets de /etc/jarvis/env.

    : "''${IRONCLAW_HOME:=/tmp/ironclaw}"
    mkdir -p "$IRONCLAW_HOME" "$HOME/.ironclaw"
    export IRONCLAW_HOME

    # Compone .env fresh en cada arranque.
    {
      echo "# generated by jarvis-chat — DO NOT EDIT (overwritten on next launch)"
      echo "DATABASE_BACKEND=libsql"
      echo "LIBSQL_PATH=$IRONCLAW_HOME/jarvis.db"
      echo "AGENT_NAME=jarvis"
      echo "HEARTBEAT_ENABLED=false"
      # IRONCLAW_PROFILE=local salta el wizard de onboard que pregunta
      # "How should IronClaw run on this machine?". El profile "local"
      # es exactamente el que pickeábamos manual cada vez (TUI + bg jobs,
      # sin Docker sandbox que en live ISO no tenemos).
      echo "IRONCLAW_PROFILE=local"
      # API keys + LLM provider del archivo de secretos.
      # Filtramos vars que ya pusimos arriba para que NUESTRA config gane.
      if [ -r /etc/jarvis/env ]; then
        grep -vE '^(DATABASE_URL|DATABASE_BACKEND|LIBSQL_|AGENT_NAME|HEARTBEAT_|IRONCLAW_PROFILE)' /etc/jarvis/env || true
      fi
    } > "$HOME/.ironclaw/.env"

    exec ${jarvisPackages.ironclaw}/bin/ironclaw "$@"
  '';
in
{
  imports = [
    # iso-image.nix: el "constructor" de ISOs. Define isoImage.* options
    # y el output system.build.isoImage que el flake expondrá como packages.iso.
    "${modulesPath}/installer/cd-dvd/iso-image.nix"
  ];

  ##################
  # Identificación #
  ##################

  isoImage = {
    # ID de volumen visible en `lsblk`/`blkid`. Solo uppercase, dígitos
    # y `_` (regla ISO9660). Confirmado 2026-04-28 que NO causa error
    # de boot — el texto rojo durante boot es solo informativo
    # (systemd buscando label antes de que el rootfs esté montado).
    volumeID = "JARVIS_OS";

    # Booteable en USB (modo híbrido isohybrid).
    makeUsbBootable = true;
    # Booteable en EFI (firmware UEFI). Crítico para el iMac 2014.
    makeEfiBootable = true;

    # Splash images del boot menu (BIOS isolinux + UEFI grub/sd-boot).
    # Renderizado del SVG canónico al boot, identidad visual desde el
    # primer pixel.
    splashImage = bootSplashPng;
    efiSplashImage = bootSplashPng;

    # Texto al lado de "NixOS Live" en el menú: identifica versión clara.
    appendToMenuLabel = " — jarvis-os v${jarvisVersion}";
  };

  # Reduce timeout del boot menu para arranque más rápido. 3s es suficiente
  # para reaccionar si quieres seleccionar opción alternativa, sin
  # esperar 10-30s del default.
  boot.loader.timeout = lib.mkForce 3;

  # En la nueva API unificada de imágenes (nixpkgs reciente) el baseName
  # se define vía `image.baseName`. Lo forzamos para que el .iso resultante
  # se llame "jarvis-os-vX.Y.Z...iso" en vez del default "nixos-...iso".
  image.baseName = lib.mkForce "jarvis-os-v${jarvisVersion}";

  ##################
  # Version label  #
  ##################

  # Archivo legible al boot con la versión exacta. Los scripts del live
  # (motd, foot welcome) lo leen para mostrarla.
  environment.etc."jarvis-version".text = ''
    jarvis-os v${jarvisVersion}
    nixos label:  ${config.system.nixos.label}
    build system: ${config.system.nixos.codeName} ${config.system.nixos.release}
  '';

  # Mensaje de TTY (issue) — visible en consolas TTY antes de Hyprland.
  # Útil si Hyprland falla y caes a TTY.
  services.getty.greetingLine = lib.mkForce
    "<<< jarvis-os v${jarvisVersion} (${config.system.nixos.label}) >>>";

  # MOTD (message of the day) — visible al login interactivo (foot, ssh).
  users.motd = ''

      jarvis-os v${jarvisVersion}
      build: ${config.system.nixos.label}

      Cmd+Enter   terminal
      Cmd+D       launcher
      Cmd+Q       cerrar ventana
      Cmd+Shift+E salir Hyprland

      ssh:  jarvis@jarvis-live.local  (password: jarvis)

  '';

  ##################
  # Filesystem RW  #
  ##################

  # En live ISO el rootfs está en squashfs read-only. NixOS monta un overlay
  # tmpfs encima para que /etc, /var, /home etc. sean escribibles en RAM.
  # Esto YA lo configura iso-image.nix; lo dejamos documentado para referencia.
  # (No hace falta tocar nada aquí.)

  ##################
  # SSH para debug #
  ##################

  # Útil mientras iteramos: si la ISO bootea pero el escritorio falla,
  # podemos entrar por SSH desde el dev box. Solo en modo pruebas.
  services.openssh = {
    enable = true;
    # SSH host key deterministic — generada una sola vez en
    # ~/.local/share/jarvis-os-secrets/ssh_host_ed25519_key, baked aquí.
    # Sin esto, cada boot live regenera keys nuevas y los clientes SSH
    # cachean la antigua → warning "REMOTE HOST IDENTIFICATION HAS CHANGED"
    # en cada test. Con este path constante, la fingerprint es estable
    # entre boots y los clientes la aprenden una sola vez.
    hostKeys = [
      {
        path = "/etc/ssh/ssh_host_ed25519_key";
        type = "ed25519";
      }
    ];
    settings = {
      PermitRootLogin = "no";
      PasswordAuthentication = true;  # solo live ISO; cambiar a keys si persistencia
    };
  };

  # Inyecta la key del secrets path al rootfs del live. Mode 0600 obligatorio
  # (sshd se niega a cargar keys con permisos más laxos).
  environment.etc."ssh/ssh_host_ed25519_key" =
    let
      keyPath = "/home/nexus/.local/share/jarvis-os-secrets/ssh_host_ed25519_key";
    in
    lib.mkIf (builtins.pathExists keyPath) {
      source = builtins.toFile "ssh_host_ed25519_key" (builtins.readFile keyPath);
      mode = "0600";
      user = "root";
      group = "root";
    };
  environment.etc."ssh/ssh_host_ed25519_key.pub" =
    let
      pubPath = "/home/nexus/.local/share/jarvis-os-secrets/ssh_host_ed25519_key.pub";
    in
    lib.mkIf (builtins.pathExists pubPath) {
      source = builtins.toFile "ssh_host_ed25519_key.pub" (builtins.readFile pubPath);
      mode = "0644";
    };

  ##################
  # NetworkManager #
  ##################

  # Asegura que NetworkManager arranca para que la WiFi del iMac esté operativa
  # desde el primer boot del live (declarado también en imac-2014.nix; es idempotente).
  networking.networkmanager.enable = lib.mkDefault true;

  ##################
  # WiFi pre-baked #
  ##################

  # Credencial WiFi inyectada al boot vía profile NetworkManager.
  # El archivo vive FUERA del repo en ~/.local/share/jarvis-os-secrets/
  # para que la psk nunca entre en git. Build necesita --impure.
  # Si el archivo no existe (otro builder), la opción queda no-op.
  environment.etc."NetworkManager/system-connections/wifi-home.nmconnection" =
    let
      secretsPath = "/home/nexus/.local/share/jarvis-os-secrets/wifi-home.nmconnection";
    in
    lib.mkIf (builtins.pathExists secretsPath) {
      text = builtins.readFile secretsPath;
      mode = "0600";
    };

  ##################
  # mDNS (.local)  #
  ##################

  # Hostname distintivo para encontrar el iMac en la LAN sin saber su IP.
  # `jarvis-live` evita colisiones si más adelante hay un `jarvis.local`
  # persistente.
  networking.hostName = lib.mkDefault "jarvis-live";

  # Avahi anuncia el host por mDNS. Tras boot, desde la otra máquina:
  #   ssh jarvis@jarvis-live.local
  services.avahi = {
    enable = true;
    nssmdns4 = true;
    publish = {
      enable = true;
      addresses = true;
      hinfo = true;
      workstation = true;
    };
  };

  # Abrir el puerto 5353 (mDNS) y 22 (SSH) en el firewall por si se activa.
  networking.firewall = {
    allowedTCPPorts = [ 22 ];
    allowedUDPPorts = [ 5353 ];
  };

  ##################
  # Stable system  #
  ##################

  # Pinear el "stateVersion" evita warnings y deja claro contra qué release
  # de NixOS se construyó. Cuando bumpeemos nixpkgs a 26.05, decidimos si
  # actualizamos esto o no (semver-ish para opciones del módulo).
  system.stateVersion = "25.05";

  ##################
  # Binarios       #
  # jarvis-os      #
  ##################

  # Binarios jarvis-os disponibles en PATH del live:
  #   jarvis-linux-mcp tools                        # lista MCP tools
  #   jarvis-linux-mcp mcp-server                   # arranca como MCP server stdio
  #   ironclaw run                                  # arranque directo del agente
  #   jarvis-chat                                   # wrapper: sourcea /etc/jarvis/env + ironclaw run
  environment.systemPackages = [
    jarvisPackages.jarvis-linux-mcp
    jarvisPackages.ironclaw
    jarvisChatScript
    startWallpaperScript
  ];

  ##################
  # API keys (env) #
  ##################

  # Bake del archivo de secretos local en /etc/jarvis/env de la ISO.
  # builtins.pathExists permite que la build funcione aunque el builder
  # no tenga el secrets path (otra persona compilando su propia ISO sin keys).
  environment.etc."jarvis/env" = lib.mkIf (builtins.pathExists jarvisEnvPath) {
    text = builtins.readFile jarvisEnvPath;
    mode = "0600";
    user = "jarvis";
    group = "users";
  };

  ##################
  # MCP register   #
  ##################

  # Servicio one-shot que registra `jarvis-linux-mcp` como MCP server en
  # IronClaw al primer login del usuario. Idempotente (ironclaw mcp add
  # no duplica si ya existe). Corre tras el bus de usuario, antes de que
  # el usuario use jarvis-chat.
  systemd.user.services.jarvis-mcp-register = {
    description = "Registrar jarvis-linux-mcp como MCP server en IronClaw";
    wantedBy = [ "default.target" ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      export IRONCLAW_HOME="''${IRONCLAW_HOME:-/tmp/ironclaw}"
      mkdir -p "$IRONCLAW_HOME" "$HOME/.ironclaw"

      # FIX v9: IronClaw lee `~/.ironclaw/.env` con dotenvy::override_load,
      # que GANA contra exports de shell. En v7/v8 el oneshot fallaba
      # silenciosamente porque no había ese .env en el momento de correr
      # (lo creaba después `jarvis-chat` la primera vez que el usuario lo
      # invocaba — círculo vicioso). Ahora lo escribimos antes nosotros.
      cat > "$HOME/.ironclaw/.env" <<EOF
      DATABASE_BACKEND=libsql
      LIBSQL_PATH=$IRONCLAW_HOME/jarvis.db
      DATABASE_URL=unused://libsql
      AGENT_NAME=jarvis
      HEARTBEAT_ENABLED=false
      EOF

      # También exportamos por si el oneshot corre en contextos donde el
      # .env no se carga (defensivo).
      export DATABASE_BACKEND=libsql
      export LIBSQL_PATH="$IRONCLAW_HOME/jarvis.db"
      export DATABASE_URL=unused://libsql

      # Sintaxis: `mcp add NAME [URL] --transport TYPE --command CMD --arg ARG`.
      # `--transport stdio` es crítico — default es http y rechaza non-HTTPS.
      # `--arg` (singular, repetible) en vez de `--args`.
      ${jarvisPackages.ironclaw}/bin/ironclaw mcp add jarvis-linux \
        --transport stdio \
        --command ${jarvisPackages.jarvis-linux-mcp}/bin/jarvis-linux-mcp \
        --arg mcp-server \
        2>&1 | tee -a "$IRONCLAW_HOME/mcp-register.log" || true
    '';
  };
}
